version: '3'

services:

  php:
    image: php:8.2-apache
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      - mysql

  python:
    image: python:3.11
    container_name: python-service
    working_dir: /app
    volumes:
      - ./python-service:/app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql